### ISSUE TITLE
Fail to build on Debian Jessie with nginx 1.12.1

### ISSUE THREAD

**Issue by yf-hk** [anjuke/ngx_http_qqwry_module#2]
Hi, thanks for your effort of making this nice module.
I was trying to compile the module from source with nginx 1.12.1. However there is an error:
```
/root/Projects/ngx_http_qqwry_module/ngx_http_qqwry_module.c: In function ‘ngx_http_qqwry_addr’:
/root/Projects/ngx_http_qqwry_module/ngx_http_qqwry_module.c:199:10: error: incompatible types when assigning to type ‘struct ngx_table_elt_t *’ from type ‘ngx_array_t’
     xfwd = r->headers_in.x_forwarded_for;
          ^
objs/Makefile:1275: recipe for target 'objs/addon/ngx_http_qqwry_module/ngx_http_qqwry_module.o' failed
```
Is it compatible with 1.12.1? How to fix that?
Thanks!
